# docker-compose.yml - Main compose file

version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: profyle-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - profyle-network

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: profyle-backend
    restart: unless-stopped
    ports:
      - '4000:4000'
    env_file:
      - backend/.env # Use .env file from backend directory
    volumes:
      - ./backend/src:/app/src:ro
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - profyle-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: profyle-frontend
    restart: unless-stopped
    ports:
      - '5173:5173'
    env_file:
      - backend/.env # Use .env file from backend directory
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - profyle-network

networks:
  profyle-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
